pipeline {
    agent any
    stages {
        stage('Newman Tests') {
            steps {
                sh '''
                cd api/newman
                newman run examen.postman_collection.json -e herokuexamen.postman_environment.json
                '''
            }
        }
    }
}