pipeline {
    agent any

    stages {
        stage('When') {
            when {
                not {
                    branch "main"
                }
            }
            steps {
                echo 'Hola'
            }
        }
        stage('GoodBye') {
            steps {
                echo 'Good Bye'
                echo 'GoodBye 3'
            }
        }
        stage('Stage3') {
            steps {
                echo 'Good Bye'
                echo 'GoodBye 4'
            }
        }
    }
}
