pipeline {
    agent any
    stages {
        stage('Newman Tests') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh '''
                    node --version
                    cd api/newman
                    newman run examen.postman_collection.json -e herokuexamen.postman_environment.json               
                    '''
                }
            }
        }
        stage('RestAssured Tests') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh '''
                        cd api/rest_assured
                        mvn clean test
                        '''
                }
            }              
        }
        stage('Jmeter Tests') {
            steps {
                sh '''
                cd load
                jmeter -n -t examen_test_plan.jmx
                '''
            }
        }
    }
}
